name: Run My Script
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # СКАЧАТЬ КОД ИЗ РЕПОЗИТОРИЯ
      - name: Checkout code
        uses: actions/checkout@v3
        
      # ЗАПУСТИТЬ СКРИПТ
      - name: Run Python script
        run: python script.py
